services:
  # Backend Service
  - type: web
    name: freelance-backend
    runtime: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: freelance-platform-secret-key-2024-production
      - key: PORT
        value: 10000
    healthCheckPath: /

  # Frontend Service
  - type: web
    name: freelance-frontend
    runtime: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm run start
    envVars:
      - key: VITE_API_URL
        sync: false
